local ssh = require("nvim-client-render.ssh")

describe("ssh", function()
  describe("parse_host", function()
    it("parses plain hostname", function()
      local parsed = ssh.parse_host("myserver")
      assert.is_nil(parsed.user)
      assert.are.equal("myserver", parsed.host)
      assert.is_nil(parsed.port)
      assert.are.equal("myserver", parsed.raw)
    end)

    it("parses user@host", function()
      local parsed = ssh.parse_host("deploy@prod.example.com")
      assert.are.equal("deploy", parsed.user)
      assert.are.equal("prod.example.com", parsed.host)
      assert.is_nil(parsed.port)
    end)

    it("parses user@host:port", function()
      local parsed = ssh.parse_host("root@10.0.0.1:2222")
      assert.are.equal("root", parsed.user)
      assert.are.equal("10.0.0.1", parsed.host)
      assert.are.equal("2222", parsed.port)
    end)

    it("parses host:port without user", function()
      local parsed = ssh.parse_host("myserver:8022")
      assert.is_nil(parsed.user)
      assert.are.equal("myserver", parsed.host)
      assert.are.equal("8022", parsed.port)
    end)

    it("handles SSH config alias (simple name)", function()
      local parsed = ssh.parse_host("devbox")
      assert.is_nil(parsed.user)
      assert.are.equal("devbox", parsed.host)
      assert.is_nil(parsed.port)
    end)

    it("preserves raw string", function()
      local raw = "user@complex-host.example.com:3333"
      local parsed = ssh.parse_host(raw)
      assert.are.equal(raw, parsed.raw)
    end)

    it("handles IPv6-style addresses without brackets", function()
      -- Simple hostname with dots (not actual IPv6 - just ensuring no crash)
      local parsed = ssh.parse_host("user@my.host.name")
      assert.are.equal("user", parsed.user)
      assert.are.equal("my.host.name", parsed.host)
      assert.is_nil(parsed.port)
    end)
  end)

  describe("get_ssh_args", function()
    it("returns nil when not connected", function()
      local args, parsed = ssh.get_ssh_args("nonexistent-host")
      assert.is_nil(args)
      assert.is_nil(parsed)
    end)
  end)

  describe("is_connected", function()
    it("returns false for unknown host", function()
      assert.is_false(ssh.is_connected("never-connected-host"))
    end)
  end)
end)
